version: "3.1"
services:
  e-selecao-admissao-postgres:
    image: postgres
    container_name: e-projeto
    volumes:
      - ./postgres-container-data/projeto_postgres_backup_dump.dump:/projeto_postgres_backup_dump.dump
      - ./postgres-container-data/projeto_postgres_backup_script.sh:/docker-entrypoint-initdb.d/projeto_postgres_backup_script.sh
    environment:
      POSTGRES_USER: projeto
      POSTGRES_PASSWORD: projeto
      POSTGRES_DB: projeto
    ports:
      - "5434:5432"

  rabbitmq:
    image: rabbitmq:management
    container_name: e-projeto-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5673:5672"  # Mapeia a porta padrão do RabbitMQ
      - "15673:15672"  # Mapeia a porta do console de administração do RabbitMQ
